import './globals.css'
import Header from "@/components/Header/Header";
import Footer from "@/components/footer/Footer";

export const metadata = {
    title: 'Home',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <header className={'fixed'}>
            <Header/>
        </header>
        <main className={'main'}>
            {children}
        </main>
        <footer className={'footer'}>
            <Footer/>
        </footer>
        </body>
        </html>
    )
}
